FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend.py  ./

RUN mkdir -p /app/chat_logs /app/pdf_store

EXPOSE 5000

CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "5000"]
